jobs:
  build:
    docker:
      - image: 31482281/codespace:latest
    # resource_class: large
    steps:
      - checkout
      - run:
         name: Run script to start building kernel
         command: ls && git clone --depth=1 https://Snax-phycho:$ght@github.com/Snax-phycho/kernel_xiaomi_tulip -b lav snx && cd snx && bash scripts/kbuild.sh