version: 2.1
jobs:
  compile:
   docker:
      - image: nexgang/ubuntu:latest
   steps:
      - run:
          command: |
           git config --global user.name "Sa Sajjad"
           git config --global user.email "mdsojola12@gmail.com"
           git config --global color.ui false
           export tg_token="$token"
           export tg_channel_id="$chat_id"
           git clone --depth=1 https://github.com/rayrzy/android_kernel_xiaomi_vince .
           bash kbuild.sh

workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
