version: 2.1
jobs:
  compile:
   docker:
      - image: nexgang/ubuntu:latest
   steps:
      - run:
          command: |
           git config --global user.name "Sa Sajjad"
           git config --global user.email "mdsojola12@gmail.com"
           git config --global color.ui false
           git clone --depth=1 https://Snax-phycho:$ght@github.com/Snax-phycho/kernel_xiaomi_lavender-4.19 -b snx .
           # bash .circleci/build.sh
           curl -s https://raw.githubusercontent.com/Sa-Sajjad/cooking_kernel/refs/heads/nyx-4.19/build.sh | bash

workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
