version: 2.1
jobs:
  compile:
   docker:
      - image: nexgang/ubuntu:latest
   steps:
      - run:
          command: |
           git config --global user.name "Sa Sajjad"
           git config --global user.email "mdsojola12@gmail.com"
           git config --global color.ui true
           git clone --depth=1 https://Snax-phycho:$ght@github.com/Snax-phycho/nexus_kernel_xiaomi_lavender -b 14 .
           bash build.sh

workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
