version: 2.1
jobs:
  compile:
   docker:
      - image: snaxpsycho/cirrus:latest
   steps:
      - run:
          command: |
           git config --global user.name "Sa Sajjad"
           git config --global user.email "mdsojola12@gmail.com"
           git config --global color.ui true
           git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
           bash .circleci/build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile