version: 2.1
jobs:
  compile:
   docker:
      - image: gitpod/workspace-full:latest
      # - image: ubuntu:22.04
   steps:
      - run:
          command: |
           git config --global user.name "Sa Sajjad"
           git config --global user.email "mdsojola12@gmail.com"
           git config --global color.ui false
           git clone --depth=1 https://Sa-Sajjad:$ght@github.com/Sa-Sajjad/kernel_xiaomi_lavender-4.19 -b wip2 kernel && cd kernel
           # sudo rm /etc/apt/sources.list.d/ondrej-ubuntu-nginx-mainline-jammy.list
           bash build.sh -up

workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
