jobs:
  build:
    docker:
      - image: 31482281/codespace:latest
    # resource_class: large
    steps:
      - checkout
      - run:
         name: Run script to start building kernel
         command: ls && git clone --depth=10 https://Snax-phycho:$ght@github.com/Snax-phycho/kernel_xiaomi_tulip -b non-qti snx && cd snx && git reset --hard HEAD~3 && bash scripts/kbuild.sh